baseURL = 'https://easydata.dev'
languageCode = 'en-us'
title = 'easydata.dev'
theme = 'hugo-book'

[markup.goldmark.renderer]
 unsafe = true

 [[params.social]]
  icon  = "icon-facebook"
  title = "Connect with me on Facebook"
  url   = "https://www.facebook.com/xyz"

[[params.social]]
  icon  = "icon-twitter"
  title = "Follow me on Twitter"
  url   = "https://twitter.com/xyz"