baseURL = 'https://easydata.dev'
languageCode = 'en-us'
title = 'easydata.dev'
theme = 'hugo-book'

[markup.goldmark.renderer]
 unsafe = true

[services]
  [services.googleAnalytics]
    ID = 'G-Z2FCNYSN7M'